### ISSUE TITLE
Whointel is not able to read logfiles containing _ (underscore) in their names

### ISSUE THREAD

**Issue by TasNavi** [whointel/WhoIntel#11]
Whointel is not able to read logfiles containing _ (underscore) in their names:

Once a logfile contains an underscore ("_") in it's name, the software is ignoring that file. LogHandler is expecting the date and time behind the first underscore in the files name, not the next letter of it's name.

**Comment by Raerten** [comment]
@TasNavi thanks for your bug report

fixed in version 0.8.15
